### ISSUE TITLE
--iface Dose nothing

### ISSUE THREAD

**Issue by csafg2** [coreos/flannel#1119]
Manually setting `--iface=enp0s8` in `kube-flannel` seems to be totally ignored.
```
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.11.0-s390x
        command:
        - /opt/bin/flanneld
        args:
        - --ip-masq
        - --kube-subnet-mgr
        - --iface=enp0s8
```
`kubectl apply -f flannel.yaml` reports everything as OK.
however when looking at logs `flannel` is still using default interface.
```
Pears@node1:~$ kubectl logs pod/kube-flannel-ds-amd64-hrgdl | grep interface
I0401 07:43:11.961053       1 main.go:514] Determining IP address of default interface
I0401 07:43:12.237615       1 main.go:527] Using interface with name enp0s3 and address 10.0.2.15
```
## Expected Behavior
`enp0s8` interface should be used.

## Current Behavior
Always uses the default interface.

## Context

I realized this issue when trying to setup a service with `ExtranalTrafficPolicy` set to cluster. and my pods were responding only on nodes where that specific pod is present

## Your Environment

* Flannel version: 
0.11
* Kubernetes version (if used):
1.14
* Operating System and version:
Ubuntu 18.04 LTS
