### ISSUE TITLE
Instructions confusing between readme and https://coreos.com/docs/cluster-management/setup/flannel-config/

### ISSUE THREAD

**Issue by jackphel** [coreos/flannel#124]
Between the readme, the docs page and different sources (https://groups.google.com/forum/#!topic/coreos-user/eo5OnvYsj3Q) I'm finding it very confusing to determine how to run flannel. I'm new to coreos but I'm having a hard time determining how you intend me to try to configure this. Is there a change coming (from that groups discussion)
that I can just set 
```
  - name: flanneld.service
      command: start
```
and it will work?

**Comment by robszumski** [comment]
Yes, the cloud-config on the docs is correct for CoreOS 554+, which is current the alpha and beta channels. I've reproduced it here:

```
#cloud-config

coreos:
  units:
    - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
      command: start
```

If you intend to use flannel and also configure docker to allow an insecure registry, a recent fix (https://github.com/coreos/bugs/issues/244) just went into the alpha channel
