### ISSUE TITLE
macvlan addresses not connectable from other subnets?

### ISSUE THREAD

**Issue by RandomGHUser** [coreos/flannel#1388]
## Problem
When I assign a macvlan address to a pod (using multus CNI), I am able to access it from the host subnet in which it is located, but I cannot access it from devices in a different subnet.

I've posted the question to the multus board (https://github.com/intel/multus-cni/issues/598), and the response is that this is a cluster network config issue.
## Steps to Reproduce (for bugs)
1. Install k8s
2. Install flannel
3. Install multus
4. Create static IP definition and deployment, example:
  ```yaml
  ---
  ### STATIC MACVLAN ADDRESS ###
  apiVersion: "k8s.cni.cncf.io/v1"
  kind: NetworkAttachmentDefinition
  metadata:
    name: static-net1
    namespace: default
  spec:
    config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.45.7.98/24",
            "gateway": "10.45.7.1"
          }
        ]
      }
    }'
  ---
  ### DEPLOYMENT ###
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nettool
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: nettool
    template:
      metadata:
        annotations:
          k8s.v1.cni.cncf.io/networks: static-net1
        namespace: default
        labels:
          name: nettool
      spec:
        containers:
          - name: nettool
            image: praqma/network-multitool
            ports:
              - containerPort: 80       
  ```

## Expected Behavior
Ability to connect to the static IP address (10.45.7.98:80) from any host on connectable subnets.
## Current Behavior
I can only connect to the pod in the same host subnet (10.45.7.0), I cannot connect to it from other subnets.  The pod can connect to hosts in other subnets:
```sh
bash-5.0# traceroute -i net1 10.45.6.18
traceroute to 10.45.6.18 (10.45.6.18), 30 hops max, 46 byte packets
 1  10.45.7.1 (10.45.7.1)  3.007 ms  1.254 ms  1.325 ms
 2  10.45.6.18 (10.45.6.18)  0.501 ms  0.644 ms  0.487 ms
bash-5.0# traceroute -i eth0 10.45.6.18
traceroute to 10.45.6.18 (10.45.6.18), 30 hops max, 46 byte packets
 1  10.244.0.1 (10.244.0.1)  0.007 ms  0.004 ms  0.003 ms
 2  10.45.7.1 (10.45.7.1)  1.054 ms  1.075 ms  0.879 ms
 3  10.45.6.18 (10.45.6.18)  0.555 ms  0.182 ms  0.547 ms
```
but the hosts in the other subnets cannot connect to it:
```sh
root@tbox:/# curl 10.45.7.98:80
curl: (7) Failed to connect to 10.45.7.98 port 80: Connection timed out
root@tbox:/# traceroute 10.45.7.98
traceroute to 10.45.7.98 (10.45.7.98), 30 hops max, 60 byte packets
 1  10.45.6.1 (10.45.6.1)  3.117 ms  2.922 ms  3.325 ms
 2  * * *
 3  * * *
 4  * * *
```
## Context
I need to be able to access this static IP address from other subnets.  My network configuration outside of kubernetes is proper, I can access this static IP proper if I use plain docker & docker-compose on the same host (example is in the question link above for reference).

## Your Environment

* Flannel version: latest (https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml)
* Kubernetes version (if used): 1.20.0
* Operating System and version: Debian 10
