### ISSUE TITLE
Unable to run flannel with remote etcd host

### ISSUE THREAD

**Issue by jonaskint** [coreos/flannel#476]
Hi,

I set up an etcd cluster in AWS with an autoscaling group that is known via route53. I am currently setting up a k8s master where the user-data looks as following:

```
#cloud-config
coreos:
  update:
    reboot-strategy: off
  flannel:
    interface: $private_ipv4
    etcd_endpoints: http://etcd.blablabla.com:2379
  units:
    - name: docker.service
      drop-ins:
        - name: 40-flannel.conf
          content: |
            [Unit]
            Requires=flanneld.service
            After=flanneld.service
    - name: flanneld.service
      drop-ins:
        - name: 10-flannel.conf
          content: |
            [Service]
            Environment="FLANNEL_VER=0.5.5"
            ExecStartPre=/usr/bin/etcdctl --peers=http://etcd.blablabla.com:2379 set /coreos.com/config/network '{"network": "172.16.0.0/16"}'
```

When the coreos vm starts, it pulls the rightt flannel version, sets the interface correctly but starts giving errors like this:
`sdnotify-proxy[694]: E0729 10:48:38.032642 00001 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [2]
`

When I look at the /run/flannel/options.env I see that the only environment variable is:
```
$ cat /run/flannel/options.env
FLANNELD_IFACE=10.13.24.178
```

So my etcd endpoint is not registered and flannel starts looking locally. I've googled this for hours and tried almost 50 times. I tried other flannel versions like the 0.2.0 and 0.5.1 as well. Does anybody know where this is coming from?
