### ISSUE TITLE
kubernetes 1.4 CNI install from daemonset

### ISSUE THREAD

**Issue by chrislovecnm** [coreos/flannel#545]
Thanks for flannel btw ... really excited to test it

1. How do I install on K8s 1.4
2. Where is the documentation

I am not running CoreOS, and I would like to install via a full Daemonset install.  I think we are moving towards a pattern, where I am able to install a DS, and voila it is installed. Other products have this bundling now.

Thanks

**Comment by luxas** [comment]
I've documented it under kubeadm is multi-platform here: 
http://kubernetes.io/docs/getting-started-guides/kubeadm/

Let me know what more you need

**Comment by chrislovecnm** [comment]
@luxas I applied that yaml and it did not appear to install the flannel binaries.  Is this the expected behavior?

**Comment by luxas** [comment]
Yes.
You need to have set `--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin` and have the cni bins in `/opt/cni/bin`

You should set `--allocate-node-cidrs=true` and `--cluster-cidr` as well in order for it to work.
If you're using the manifest linked below, you should set `--cluster-cidr=10.244.0.0/16`.

The manifest will use the flannel binary in `/opt/cni/bin` and put a file in `/etc/cni/net.d`.
Would love to have a doc of this as well.

**Comment by chrislovecnm** [comment]
> The manifest will use the flannel binary in /opt/cni/bin and put a file in /etc/cni/net.d.
Would love to have a doc of this as well.

The binary did not get installed by the ds

**Comment by luxas** [comment]
That's not expected either. 
All binaries should be present on-host before (flannel is one of the "official" binaries in the CNI tarball)

**Comment by chrislovecnm** [comment]
@luxas which tar ball are you referring to ... can you ping me on slack?

**Comment by chrislovecnm** [comment]
Also is flannel compatible with etcd 3 yet?

**Comment by autostatic** [comment]
The kube-flannel.yml in the Documentation directory does not work with Kubernetes 1.4. Check out #535 
You will need the following set for CNI:
```  cni-conf.json: |
    {
      "name": "cbr0",
      "type": "flannel",
      "delegate": {
        "bridge": "cbr0",
        "forceAddress": true,
        "isDefaultGateway": true
      }
    }```
And keep in mind that the CIDR you use for your pod network is large enough, a three node cluster needs at least a /22 for instance as each node gets assigned a /24.

**Comment by garryknox** [comment]
@luxas  you wrote

> You need to have set --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin and have the cni bins in /opt/cni/bin
> 
> You should set --allocate-node-cidrs=true and --cluster-cidr as well in order for it to work.

 Where do you set these values?

 Thanks.

**Comment by garryknox** [comment]
I can answer the first part of my question. I see the cni parameters are part of the KUBELET_NETWORK_ARGS environment variables in my 10-kubeadm.conf file -- which is part of the kubeadm package install I used. I'm still tracking down --allocate-node-cidrs=true and --cluster-cidr .

 2nd question. Does the Flannel daemonset use etcd still?

**Comment by autostatic** [comment]
@garryknox Those options are in `/etc/kubernetes/manifests/kube-controller-manager.json` on the K8s master. I think you can set those when using the `--pod-network-cidr` option with `kubeadm init`. And the Flannel DaemonSet needs etcd as Flannel is strarted with the `-kube-subnet-mgr` option. This is a call to the kube-apiserver which in its turn gets its info from etcd.

**Comment by garryknox** [comment]
@autostatic Thanks. 

 Regarding etcd. I see the etcd urls I passed into kubeadm init are in the kube-apiserver conf file. My pod network seems to work fine but I don't see flannel subnets in my etcd db. Usually with flanneld you can set the  etch-prefix -- is there a way to do this with kubeadm+flannel daemonset?

**Comment by CaesarC** [comment]
@garryknox agree~

**Comment by CaesarC** [comment]
@garryknox i have the same problem too.
i have to build a machine whit flanned alone. but i can join the kube cluster newwork.
in kube 1.2 i usually star flanned with etcd whit key prefix /coreos.com/network
```
E1205 17:13:22.380516 08865 network.go:106] failed to retrieve network config: 100: Key not found (/coreos.com) [10267]
```

**Comment by autostatic** [comment]
@garryknox Yes that's possible. You have to update the `net-conf.json` config in the `kube-flannel.yaml` file:
```  net-conf.json: |
    {
      "Network": "10.244.0.0/22",
      "SubnetLen": 24,
      "Backend": {
        "Type": "vxlan"
      }
    }
```
And you also have to the tell the running etcd service that it has to use this Flannel network and subnet. You can do this with a `curl` command that reads the values from a JSON file. The contents of the JSON file should look like this:
```{
  "Network": "10.244.0.0/22",
  "SubnetLen": 24,
  "Backend": {"Type": "vxlan"
  }
}
```
Save this as `flannel-config.json` and load it into etcd with:
`curl -L http://127.0.0.1:2379/v2/keys/coreos.com/network/config -XPUT --data-urlencode value@/root/kubernetes/flannel-config.json`
Make sure the Fkannel network you're using is the same as the network you've set with `--pod-network-cidr`!

**Comment by abessifi** [comment]
@autostatic I still not able to run flannel across my cluster. could you please tell us:
- what is the version of kubernetes you are using ?
- the docker version ?
- what is the complete content of the kube-flannel.yaml file ?

**Comment by autostatic** [comment]
@abessifi 

- Kubernetes 1.4.4, but it should work with any 1.4 release
- Docker 1.12.1, but I don't think this is relevant
- Complete content of `kube-flannel.yaml`: https://gist.github.com/autostatic/6dcb0f28ac7da2eb8ae9d4b553479228

I do use a patched Flannel otherwise I can't get the K8s master to talk to pods on other nodes. Drawback of this patch is that the first available Flannel gets skipped, so in this specific case 10.244.0.0/24 gets skipped and 10.244.1.0/24 gets assigned first.

**Comment by xiaoping378** [comment]
should i modify manually docker.service ?
due to it depends the /run/flannel/subnet.env

**Comment by autostatic** [comment]
That's not necessary when using Flannel as a CNI add-on as it doesn't depend on `/run/flannel/subnet.env`.

**Comment by xiaoping378** [comment]
Thanks, i got it.
i missing --pod-network-cidr=10.244.0.0/16

**Comment by xiaoping378** [comment]
But the the kube-dns always output
```
Get https://10.96.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.96.0.1:443: getsockopt: no route to host
```
my host route:
```
[root@node0 ~]# ip route
default via 192.168.31.1 dev enp0s8  proto static  metric 100 
10.244.0.0/24 dev cni0  proto kernel  scope link  src 10.244.0.1 
10.244.0.0/16 dev flannel.1  proto kernel  scope link  src 10.244.0.0 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
192.168.31.0/24 dev enp0s8  proto kernel  scope link  src 192.168.31.102  metric 100 
192.168.56.0/24 dev enp0s3  proto kernel  scope link  src 192.168.56.110  metric 100 
```

Don't understand this error, @autostatic  help.

**Comment by xiaoping378** [comment]
OK, worked as below:
1. disable selinux,
2.  change cni-conf.json
![image](https://cloud.githubusercontent.com/assets/5623173/21209983/b2d0ce6e-c2b2-11e6-8a35-d0dd12e8c9d2.png)

**Comment by abessifi** [comment]
@xiaoping378 
Could you please point out your complete `kube-flannel.yaml` file ?

**Comment by xiaoping378** [comment]
```yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "type": "flannel",
      "delegate": {
        "bridge": "cbr0",
        "isDefaultGateway": true,
        "hairpinMode": true,
        "forceAddress": true
      }
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
  namespace: kube-system
  labels:
    tier: node
    app: flannel
spec:
  template:
    metadata:
      labels:
        tier: node
        app: flannel
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel-git:latest
        imagePullPolicy: IfNotPresent
        command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr" ]
        securityContext:
          privileged: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: run
          mountPath: /run
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      - name: install-cni
        image: quay.io/coreos/flannel-git:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh", "-c", "set -e -x; cp -f /etc/kube-flannel/cni-conf.json /etc/cni/net.d/10-flannel.conf; while true; do sleep 3600; done" ]
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
        - name: run
          hostPath:
            path: /run
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: flannel-cfg
          configMap:
            name: kube-flannel-cfg
```
