### ISSUE TITLE
flannel cannot be used with the docker-latest package on redhat based system

### ISSUE THREAD

**Issue by djsly** [coreos/flannel#557]
To use the official package from redhat `docker-latest` describe here: https://access.redhat.com/articles/2317361

I needed to copy the following file to a new location and edit the flannel.service

flanneld.service changes

replaced
```
 EnvironmentFile=-/etc/sysconfig/docker-network
```
by
```
 EnvironmentFile=-/etc/sysconfig/docker-latest-network
```

and

```
RequiredBy=docker.service
```
by
```
RequiredBy=docker-latest.service
```

I also duplicated the `flannel.conf` under `docker.service.d` to allow `docker-latest` to inherit from the flannel conf.

```
 duplicate_docker_dot_d_conf:
     file.copy:
         - name: /usr/lib/systemd/system/docker-latest.service.d/flannel.conf
         - source: /usr/lib/systemd/system/docker.service.d/flannel.conf
         - force: True
         - makedirs: True
         - preserve: True
```

I understand that this package is not the recommended official docker but it might be beneficial for kubernetes users to be allowed to use the Os provided docker latest. 

If I write a PR to try to support both packages on centOS, where would be the right place to do so ? 

Thanks
