### ISSUE TITLE
flannel cni plugin uses real hostname not the name of the node

### ISSUE THREAD

**Issue by mrahbar** [coreos/flannel#664]
Versions.

v0.7.0-amd64

Repro steps.

Kubernetes setup: 
- Deploy flannel as cni plugin via a DeamonSet (extract):
```
          hostNetwork: true
        - name: kube-flannel
          image: quay.io/coreos/flannel:{{ canal_flannel_version }}
          command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr" ]
          securityContext:
            privileged: true
```
- Configure kube-controller-manager and kubelet

 systemctl status kubelet -l
`/usr/bin/kubelet [...]  --hostname-override=KubeMaster03 --cni-bin-dir=/opt/cni/bin --cni-conf-dir=/etc/cni/net.d --network-plugin=cni --network-plugin-dir=/etc/cni/net.d `

`/usr/bin/kube-controller-manager [...] --allocate-node-cidrs=true --cluster-cidr=172.16.0.0/16`

- Verify node cidr's are distributed:

````
 kubectl get node -o yaml | grep -E "(externalID|podCIDR)"
    externalID: kubemaster02
    podCIDR: 172.16.238.0/24
    externalID: kubemaster03
    podCIDR: 172.16.239.0/24
    externalID: kubenodebackend01
    podCIDR: 172.16.240.0/24
    externalID: kubenodefrontend01
    podCIDR: 172.16.245.0/24
````
- Starting a container and let flannel cni plugin associate pod IP leads to pod status CrashLoopBackOff with error:

> Error syncing pod, skipping: failed to "CreatePodSandbox" for "kube-dns-1492517805-45kv7_kube-system(71d6eaf9-1979-11e7-ae5d-fa163e06df03)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-dns-1492517805-45kv7_kube-system(71d6eaf9-1979-11e7-ae5d-fa163e06df03)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"kube-dns-1492517805-45kv7_kube-system\" network: nodes \"kubernetes-cluster-kubemaster03-edjh7jnebspu.novalocal\" not found"

- Resolution:
Change hostname of node to same value of _hostname-override_ of kubelet

- Culprit:
 > https://github.com/coreos/flannel/blob/master/subnet/kube/kube.go#L201

Value of nodeName is not populated from pod.Spec.NodeName as it should be.
