### ISSUE TITLE
kube-subnet-mgr doens't work with nodes that have empty annotation

### ISSUE THREAD

**Issue by tomdee** [coreos/flannel#818]
I hit this during some manual testing. This could be a completely synthetic situation so I'm interested to hear if people think it can be hit in the field.

The following node manifest works:
```
apiVersion: v1
kind: Node
metadata:
  name: flannel1
  annotations:
    dummy: value
spec:
  podCIDR: 10.10.1.0/24
```

If I remove the annotations key completely then flannel fails to start.

## Expected Behavior
Flannel should start

## Current Behavior
Flannel fails to start.

## Steps to Reproduce (for bugs)
Run flannel again a node with this minimal config
```
apiVersion: v1
kind: Node
metadata:
  name: flannel1
spec:
  podCIDR: 10.10.1.0/24
```
## Context
As I mentioned above, I'm not sure if this is a real problem or just synthetic. I only hit it when manually creating nodes, and maybe it can never be hit when the kubelet creates the node.

## Your Environment
* Flannel version: Any with kube-subnet-mgr support
* Backend used: any
* Etcd version: na
* Kubernetes version (if used): any
